<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="MyDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sql.bsite.net\MSSQL2016;Persist Security Info=True;User ID=phucpq_PHUCPQ" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tb_User" Member="Tb_Users">
    <Type Name="Tb_User">
      <Column Name="IdUser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[_Password]" Member="_Password" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Permission" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="[_Address]" Member="_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Sp_01_GetUserByUserNameAndPassword" Method="Sp_01_GetUserByUserNameAndPassword">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="Sp_01_GetUserByUserNameAndPasswordResult">
      <Column Name="IdUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[_Password]" Member="_Password" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Permission" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="[_Address]" Member="_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>