USE [master]
GO
/****** Object:  Database [phucpq_PHUCPQ]    Script Date: 31/07/2022 8:28:58 PM ******/
CREATE DATABASE [phucpq_PHUCPQ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'phucpq_PHUCPQ', FILENAME = N'D:\sql-freeasphost-user-dbs\phucpq_PHUCPQ.mdf' , SIZE = 10240KB , MAXSIZE = 51200KB , FILEGROWTH = 5120KB )
 LOG ON 
( NAME = N'phucpq_PHUCPQ_log', FILENAME = N'D:\sql-freeasphost-user-dbs\phucpq_PHUCPQ.ldf' , SIZE = 5120KB , MAXSIZE = 25600KB , FILEGROWTH = 5120KB )
GO
ALTER DATABASE [phucpq_PHUCPQ] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [phucpq_PHUCPQ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [phucpq_PHUCPQ] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET ARITHABORT OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET  ENABLE_BROKER 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET RECOVERY FULL 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET  MULTI_USER 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [phucpq_PHUCPQ] SET DB_CHAINING OFF 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [phucpq_PHUCPQ] SET QUERY_STORE = OFF
GO
USE [phucpq_PHUCPQ]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [phucpq_PHUCPQ]
GO
/****** Object:  Table [dbo].[Tb_User]    Script Date: 31/07/2022 8:29:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tb_User](
	[IdUser] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](100) NULL,
	[_Password] [nvarchar](100) NULL,
	[Permission] [nvarchar](100) NULL,
	[FullName] [nvarchar](500) NULL,
	[_Address] [nvarchar](500) NULL,
	[Avatar] [nvarchar](1000) NULL,
 CONSTRAINT [PK_Tb_User] PRIMARY KEY CLUSTERED 
(
	[IdUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Tb_User] ON 
GO
INSERT [dbo].[Tb_User] ([IdUser], [Username], [_Password], [Permission], [FullName], [_Address], [Avatar]) VALUES (3, N'phuc', N'123', N'admin', N'Phạm Quang Phúc Phúc', N'erere', NULL)
GO
INSERT [dbo].[Tb_User] ([IdUser], [Username], [_Password], [Permission], [FullName], [_Address], [Avatar]) VALUES (11, N'thongthong', N'123', N'admin', N'Chu Bá ', N'aqweqwe', NULL)
GO
SET IDENTITY_INSERT [dbo].[Tb_User] OFF
GO
/****** Object:  StoredProcedure [dbo].[Sp_01_GetUserByUserNameAndPassword]    Script Date: 31/07/2022 8:29:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Proc [dbo].[Sp_01_GetUserByUserNameAndPassword](@Username nvarchar(100), @Password nvarchar(100))
as
begin
Select * From Tb_User  U where U.Username = @Username and U._Password = @Password
end
GO
USE [master]
GO
ALTER DATABASE [phucpq_PHUCPQ] SET  READ_WRITE 
GO
